{% set name = "pymolpro" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/molpro/pymolpro/archive/{{ version }}.tar.gz
  sha256: d1e3740909c9eb84b29a498f65809d8f7d8725b7deccc5b41d67c4c80a05b543

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - versioneer
    - pip
    - scipy
  run:
    - python >=3.6
    - pysjef >=1.29.2
    - numpy >=1.12
    - regex
    - scipy

test:
  imports:
    - pymolpro
  commands:
    - pip check
  requires:
    - pip

about:
  license: MIT
  license_file: LICENSE
  home: https://github.com/molpro/pymolpro
  summary: Python package supporting Molpro quantum chemistry
  doc_url: https://molpro.github.io/pymolpro
  doc_source_url: https://github.com/molpro/pymolpro/blob/master/README.rst
  description: |
    pymolpro is a Python library that provides support for working with the Molpro quantum chemistry package.
    The principal feature is
    the `Project` class that provides access to a complete Molpro job, including input
    and output files together with metadata such as job status information.

extra:
  recipe-maintainers:
    - nick-wilson
    - pjknowles
    - molpro-owner
