{% set name = "pymolpro" %}
{% set version = "1.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/molpro/pymolpro/archive/{{ version }}.tar.gz
  sha256: 3ea7bdf5d74dd92f8e55deb530bee4cd4c5f82a6f410afef6e2fff61620afc53

build:
  noarch: python
  script: |
    git init
    git config user.name nobody
    git config user.email a@b.com
    git add .
    git commit -am .
    git tag {{ version }}
    {{ PYTHON }} -m pip install . -vv
    cp pymolpro/run_molpro.py $PREFIX/bin/run_molpro.py
    cp pymolpro/run_molpro.py $PREFIX/bin/run_molpro
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - scipy >=1.9.3
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - pysjef >=1.42.3
    - numpy
    - regex
    - scipy >=1.9.3
    - chemcoord
    - quadpy
    - ase
    - jsonschema >=4.0.0
    - pandas <3

test:
  imports:
    - pymolpro
  commands:
    - pip check || true
  requires:
    - pip
    - python {{ python_min }}

about:
  license: MIT
  license_file: LICENSE
  home: https://github.com/molpro/pymolpro
  summary: Python package supporting Molpro quantum chemistry
  doc_url: https://molpro.github.io/pymolpro
  doc_source_url: https://github.com/molpro/pymolpro/blob/master/README.rst
  description: |
    pymolpro is a Python library that provides support for working with the Molpro quantum chemistry package.
    The principal feature is
    the `Project` class that provides access to a complete Molpro job, including input
    and output files together with metadata such as job status information.

extra:
  recipe-maintainers:
    - pjknowles
    - molpro-owner
