{% set name = "pymolpro" %}
{% set version = "1.15.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/molpro/pymolpro/archive/{{ version }}.tar.gz
  sha256: f0b32175e6a1302bb229446ccf01701df8bc3381af45d32cc2935017d8ab52ac

build:
  noarch: python
  script: |
    git init
    git config user.name nobody
    git config user.email a@b.com
    git add .
    git commit -am .
    git tag {{ version }}
    {{ PYTHON }} -m pip install . -vv
    cp pymolpro/molpro_input.py $PREFIX/bin/molpro_input.py
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - scipy
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - pysjef >=1.41.2
    - numpy
    - regex
    - scipy
    - chemcoord
    - quadpy
    - ase
    - jsonschema

test:
  imports:
    - pymolpro
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  license: MIT
  license_file: LICENSE
  home: https://github.com/molpro/pymolpro
  summary: Python package supporting Molpro quantum chemistry
  doc_url: https://molpro.github.io/pymolpro
  doc_source_url: https://github.com/molpro/pymolpro/blob/master/README.rst
  description: |
    pymolpro is a Python library that provides support for working with the Molpro quantum chemistry package.
    The principal feature is
    the `Project` class that provides access to a complete Molpro job, including input
    and output files together with metadata such as job status information.

extra:
  recipe-maintainers:
    - pjknowles
    - molpro-owner
