{% set name = "pymolpro" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/molpro/pymolpro/archive/{{ version }}.tar.gz
  sha256: d01039bae07287a40ab25eeef550775fd01f39a6b64ad1aff544772795635a1c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - versioneer
    - pip
  run:
    - python >=3.6
    - pysjef >=1.23.0
    - numpy >=1.12
    - regex

test:
  imports:
    - pymolpro
  commands:
    - pip check
  requires:
    - pip

about:
  license: MIT
  license_file: LICENSE
  home: https://github.com/molpro/pymolpro
  summary: Python package supporting Molpro quantum chemistry

extra:
  recipe-maintainers:
    - nick-wilson
    - pjknowles
    - molpro-owner
