{% set name = "pymolpro" %}
{% set version = "1.3.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/molpro/pymolpro/archive/{{ version }}.tar.gz
  sha256: 782ee31354e5b1ad9ff388c6c6793679383fbad613a66e26f3ec8708da2763f9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - versioneer
    - pip
    - scipy
  run:
    - python >=3.6
    - pysjef >=1.31.0
    - numpy >=1.12
    - regex
    - scipy

test:
  imports:
    - pymolpro
  commands:
    - pip check
  requires:
    - pip

about:
  license: MIT
  license_file: LICENSE
  home: https://github.com/molpro/pymolpro
  summary: Python package supporting Molpro quantum chemistry
  doc_url: https://molpro.github.io/pymolpro
  doc_source_url: https://github.com/molpro/pymolpro/blob/master/README.rst
  description: |
    pymolpro is a Python library that provides support for working with the Molpro quantum chemistry package.
    The principal feature is
    the `Project` class that provides access to a complete Molpro job, including input
    and output files together with metadata such as job status information.

extra:
  recipe-maintainers:
    - nick-wilson
    - pjknowles
    - molpro-owner
