{% set name = "pymolpro" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/molpro/pymolpro/archive/{{ version }}.tar.gz
  sha256: e39d467cf1fc8c5b1eca91fe485430adf15764d8728ae5f48f62632976c7b613

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - versioneer
    - pip
  run:
    - python >=3.6
    - pysjef >=1.23.0
    - numpy >=1.12
    - regex

test:
  imports:
    - pymolpro
  commands:
    - pip check
  requires:
    - pip

about:
  license: MIT
  license_file: LICENSE
  home: https://github.com/molpro/pymolpro
  summary: Python package supporting Molpro quantum chemistry
  doc_url: https://molpro.github.io/pymolpro
  doc_source_url: https://github.com/molpro/pymolpro/blob/master/README.rst
  description: |
    pymolpro is a Python library that provides support for working with the Molpro quantum chemistry package.
    The principal feature is
    the `Project` class that provides access to a complete Molpro job, including input
    and output files together with metadata such as job status information.

extra:
  recipe-maintainers:
    - nick-wilson
    - pjknowles
    - molpro-owner
